// =====================================================
// MindQuark — data, courses, webinars, i18n
// =====================================================

const I18N = {
  it: {
    nav: { home: 'Home', courses: 'Corsi', webinar: 'Webinar', about: 'Chi sono', dashboard: 'Area studente' },
    cta_book: 'Prenota una call',
    cta_start: 'Inizia ora',
    cta_browse: 'Esplora i corsi',
    hero_kicker: 'Ciao, sono',
    hero_role: 'Matematica e Fisica Teorica · Tutor & Webinar',
    hero_sub: 'Aiuto studenti di liceo e università a superare esami, recuperare debiti e capire davvero la materia. Lezioni on-demand, webinar live e materiali scaricabili.',
    badge_live: 'In diretta',
    badge_ondemand: 'On-demand',
    badge_download: 'Scaricabile',
    badge_one2one: 'One to one',
    badge_group: 'Di gruppo',
    section_subjects: 'Materie',
    section_subjects_sub: 'Dall\'analisi all\'elettromagnetismo. Costruisci il tuo percorso o segui quelli pronti.',
    section_courses: 'Corsi consigliati',
    section_courses_sub: 'Lezioni registrate + dispense + esercizi corretti. Accesso illimitato.',
    section_webinar: 'Prossimi webinar',
    section_webinar_sub: 'Sessioni live, posti limitati. Tutto registrato e scaricabile dopo.',
    section_how: 'Come funziona',
    section_how_sub: 'Tre modi per studiare con me. Scegli il tuo ritmo.',
    section_testimonials: 'Risultati degli studenti',
    section_testimonials_sub: '740+ esami superati, 92% di promossi al primo tentativo.',
    section_about: 'Chi sono',
    section_cta: 'Prossimo esame?',
    section_cta_sub: 'Prenota una call gratuita di 20 minuti. Ti dico se posso aiutarti e come.',
    learn_more: 'Scopri di più',
    enroll: 'Iscriviti',
    book_seat: 'Prenota posto',
    watch_now: 'Guarda ora',
    download: 'Scarica MP4',
    add_calendar: 'Aggiungi al calendario',
    starts_in: 'Inizia tra',
    days: 'g', hours: 'h', minutes: 'm', seconds: 's',
    seats_left: 'posti disponibili',
    sold_out: 'Esaurito',
    duration: 'Durata',
    lessons: 'Lezioni',
    level: 'Livello',
    students: 'Studenti',
    rating: 'Valutazione',
    instructor: 'Docente',
    includes: 'Cosa è incluso',
    syllabus: 'Programma',
    reviews: 'Recensioni',
    buy_now: 'Acquista ora',
    add_cart: 'Aggiungi al carrello',
    in_cart: 'Nel carrello',
    total: 'Totale',
    proceed: 'Procedi al pagamento',
    payment: 'Pagamento',
    confirm_pay: 'Conferma e paga',
    order_complete: 'Ordine completato',
    order_complete_sub: 'Trovi i tuoi corsi nell\'area studente. Buono studio!',
    go_dashboard: 'Vai all\'area studente',
    my_courses: 'I miei corsi',
    progress: 'Progresso',
    continue: 'Continua',
    next_lesson: 'Prossima lezione',
    materials: 'Materiali',
    chat_live: 'Chat live',
    send: 'Invia',
    type_message: 'Scrivi un messaggio…',
    free_call: 'Call gratuita 20 min',
    or: 'oppure',
    months: 'mesi',
    plan_single: 'Singolo corso',
    plan_pass: 'Pass mensile',
    plan_pass_sub: 'Accesso a tutti i corsi + 2 webinar/mese',
    plan_one2one: 'Tutoring 1-1',
    plan_one2one_sub: '4 sessioni private da 60 minuti',
    most_popular: 'Più scelto',
    onboarding_title: 'Crea il tuo account',
    onboarding_sub: 'Inizia il tuo percorso. Ricevi aggiornamenti su corsi, webinar e materiali esclusivi.',
    onboarding_name: 'Nome completo',
    onboarding_email: 'Email',
    onboarding_password: 'Password',
    onboarding_confirm: 'Conferma password',
    onboarding_level: 'Il tuo livello',
    onboarding_level_sub: 'Così posso consigliarti i corsi giusti',
    onboarding_level_high: 'Liceo / Scuola superiore',
    onboarding_level_uni: 'Università',
    onboarding_level_adult: 'Professionista / Autodidatta',
    onboarding_interests: 'I tuoi interessi',
    onboarding_interests_sub: 'Scegli le materie che ti interessano (puoi cambiarle dopo)',
    onboarding_terms: 'Accetto i termini di servizio e la privacy policy',
    onboarding_submit: 'Crea account',
    onboarding_success: 'Account creato!',
    onboarding_success_sub: 'Ora puoi accedere all\'area studente e iniziare subito.',
    onboarding_login: 'Hai già un account? Accedi',
    onboarding_login_link: 'Accedi',
    onboarding_placeholder_name: 'es. Mario Rossi',
    onboarding_placeholder_email: 'es. mario@email.com',
    onboarding_password_note: 'Minimo 8 caratteri',
    onboarding_step_1: 'I tuoi dati',
    onboarding_step_2: 'Di dove sei',
    onboarding_step_3: 'Cosa ti interessa',
    onboarding_skip: 'Salta',
    onboarding_prev: 'Indietro',
    onboarding_next: 'Continua',
    onboarding_go_dashboard: 'Vai all\'area studente',
    onboarding_nav: 'Accedi / Registrati',
    footer_tag: 'Studia con metodo. Capisci davvero.',
    cookies: 'Cookie',
    privacy: 'Privacy',
    terms: 'Termini',
  },
  en: {
    nav: { home: 'Home', courses: 'Courses', webinar: 'Webinars', about: 'About', dashboard: 'Student area' },
    cta_book: 'Book a call',
    cta_start: 'Get started',
    cta_browse: 'Browse courses',
    hero_kicker: 'Hello, I am',
    hero_role: 'Math & Theoretical Physics · Tutor & Webinars',
    hero_sub: 'I help high-school and university students pass exams, recover credits and actually understand the subject. On-demand lessons, live webinars and downloadable materials.',
    badge_live: 'Live',
    badge_ondemand: 'On-demand',
    badge_download: 'Downloadable',
    badge_one2one: 'One to one',
    badge_group: 'Group',
    section_subjects: 'Subjects',
    section_subjects_sub: 'From analysis to electromagnetism. Build your own path or follow a ready-made one.',
    section_courses: 'Recommended courses',
    section_courses_sub: 'Recorded lessons + notes + corrected exercises. Unlimited access.',
    section_webinar: 'Upcoming webinars',
    section_webinar_sub: 'Live sessions, limited seats. Recorded and downloadable afterwards.',
    section_how: 'How it works',
    section_how_sub: 'Three ways to study with me. Pick your pace.',
    section_testimonials: 'Student results',
    section_testimonials_sub: '740+ exams passed, 92% pass rate on the first try.',
    section_about: 'About me',
    section_cta: 'Got an exam coming?',
    section_cta_sub: 'Book a free 20-min call. I\'ll tell you if and how I can help.',
    learn_more: 'Learn more',
    enroll: 'Enroll',
    book_seat: 'Book a seat',
    watch_now: 'Watch now',
    download: 'Download MP4',
    add_calendar: 'Add to calendar',
    starts_in: 'Starts in',
    days: 'd', hours: 'h', minutes: 'm', seconds: 's',
    seats_left: 'seats left',
    sold_out: 'Sold out',
    duration: 'Duration',
    lessons: 'Lessons',
    level: 'Level',
    students: 'Students',
    rating: 'Rating',
    instructor: 'Instructor',
    includes: 'What\'s included',
    syllabus: 'Syllabus',
    reviews: 'Reviews',
    buy_now: 'Buy now',
    add_cart: 'Add to cart',
    in_cart: 'In cart',
    total: 'Total',
    proceed: 'Proceed to payment',
    payment: 'Payment',
    confirm_pay: 'Confirm & pay',
    order_complete: 'Order complete',
    order_complete_sub: 'Your courses are in the student area. Happy studying!',
    go_dashboard: 'Go to student area',
    my_courses: 'My courses',
    progress: 'Progress',
    continue: 'Continue',
    next_lesson: 'Next lesson',
    materials: 'Materials',
    chat_live: 'Live chat',
    send: 'Send',
    type_message: 'Type a message…',
    free_call: 'Free 20-min call',
    or: 'or',
    months: 'months',
    plan_single: 'Single course',
    plan_pass: 'Monthly pass',
    plan_pass_sub: 'Access to all courses + 2 webinars/month',
    plan_one2one: '1-1 tutoring',
    plan_one2one_sub: '4 private 60-min sessions',
    most_popular: 'Most popular',
    onboarding_title: 'Create your account',
    onboarding_sub: 'Start your journey. Get updates on courses, webinars and exclusive materials.',
    onboarding_name: 'Full name',
    onboarding_email: 'Email',
    onboarding_password: 'Password',
    onboarding_confirm: 'Confirm password',
    onboarding_level: 'Your level',
    onboarding_level_sub: 'So I can recommend the right courses for you',
    onboarding_level_high: 'High school',
    onboarding_level_uni: 'University',
    onboarding_level_adult: 'Professional / Self-taught',
    onboarding_interests: 'Your interests',
    onboarding_interests_sub: 'Pick subjects you are interested in (you can change later)',
    onboarding_terms: 'I accept the terms of service and privacy policy',
    onboarding_submit: 'Create account',
    onboarding_success: 'Account created!',
    onboarding_success_sub: 'You can now access the student area and start right away.',
    onboarding_login: 'Already have an account?',
    onboarding_login_link: 'Log in',
    onboarding_placeholder_name: 'e.g. Mario Rossi',
    onboarding_placeholder_email: 'e.g. mario@email.com',
    onboarding_password_note: 'Minimum 8 characters',
    onboarding_step_1: 'Your details',
    onboarding_step_2: 'Your level',
    onboarding_step_3: 'Your interests',
    onboarding_skip: 'Skip',
    onboarding_prev: 'Back',
    onboarding_next: 'Continue',
    onboarding_go_dashboard: 'Go to student area',
    onboarding_nav: 'Sign up / Log in',
    footer_tag: 'Study with method. Really understand.',
    cookies: 'Cookies',
    privacy: 'Privacy',
    terms: 'Terms',
  }
};

// Subjects (Materie)
const SUBJECTS = [
  { id: 'analisi', glyph: '∫', it: 'Analisi matematica', en: 'Calculus', courses: 6, color: '#2563EB', tag: 'MATH' },
  { id: 'algebra', glyph: 'A', it: 'Algebra lineare', en: 'Linear Algebra', courses: 4, color: '#7C3AED', tag: 'MATH' },
  { id: 'geometria', glyph: '△', it: 'Geometria', en: 'Geometry', courses: 3, color: '#0891B2', tag: 'MATH' },
  { id: 'meccanica', glyph: 'F', it: 'Meccanica classica', en: 'Classical Mechanics', courses: 5, color: '#059669', tag: 'PHYS' },
  { id: 'em', glyph: '∇', it: 'Elettromagnetismo', en: 'Electromagnetism', courses: 4, color: '#D97706', tag: 'PHYS' },
  { id: 'qm', glyph: 'ψ', it: 'Meccanica quantistica', en: 'Quantum Mechanics', courses: 3, color: '#DC2626', tag: 'PHYS' },
  { id: 'rel', glyph: 'c²', it: 'Relatività', en: 'Relativity', courses: 2, color: '#0d1220', tag: 'PHYS' },
  { id: 'maturita', glyph: '✦', it: 'Preparazione maturità', en: 'High-school finals prep', courses: 4, color: '#2563EB', tag: 'PREP' },
  { id: 'tolc', glyph: '◎', it: 'Test ammissione', en: 'University entrance', courses: 3, color: '#7C3AED', tag: 'PREP' },
];

// Courses
const COURSES = [
  {
    id: 'analisi-1',
    title_it: 'Analisi 1 — dal limite agli integrali',
    title_en: 'Calculus 1 — from limits to integrals',
    subject: 'analisi',
    level_it: 'Universitario · Base',
    level_en: 'University · Beginner',
    duration: '38h',
    lessons: 42,
    students: 1240,
    rating: 4.9,
    price: 149,
    type: 'ondemand',
    thumb: 'analisi',
    short_it: 'Tutto il programma di Analisi 1: limiti, derivate, integrali, serie. Con 200+ esercizi svolti.',
    short_en: 'The full Calculus 1 syllabus: limits, derivatives, integrals, series. With 200+ solved exercises.',
    tags_it: ['Università', 'Esame', 'On-demand'],
    tags_en: ['University', 'Exam', 'On-demand'],
    syllabus_it: [
      { ch: '01', t: 'Numeri reali e successioni', m: '4h 20m' },
      { ch: '02', t: 'Limiti di funzione', m: '5h 10m' },
      { ch: '03', t: 'Continuità', m: '3h 30m' },
      { ch: '04', t: 'Derivate e applicazioni', m: '6h 45m' },
      { ch: '05', t: 'Studio di funzione', m: '4h 15m' },
      { ch: '06', t: 'Integrali indefiniti', m: '5h 30m' },
      { ch: '07', t: 'Integrali definiti e impropri', m: '4h 50m' },
      { ch: '08', t: 'Serie numeriche', m: '4h 00m' },
    ],
  },
  {
    id: 'algebra-lin',
    title_it: 'Algebra Lineare per ingegneri',
    title_en: 'Linear Algebra for engineers',
    subject: 'algebra',
    level_it: 'Universitario · Base',
    level_en: 'University · Beginner',
    duration: '24h',
    lessons: 28,
    students: 890,
    rating: 4.8,
    price: 119,
    type: 'ondemand',
    thumb: 'algebra',
    short_it: 'Matrici, sistemi lineari, autovalori, diagonalizzazione. Approccio pratico per ingegneria.',
    short_en: 'Matrices, linear systems, eigenvalues, diagonalization. Practical engineering approach.',
    tags_it: ['Università', 'Ingegneria', 'On-demand'],
    tags_en: ['University', 'Engineering', 'On-demand'],
  },
  {
    id: 'meccanica-1',
    title_it: 'Fisica 1 — Meccanica classica',
    title_en: 'Physics 1 — Classical Mechanics',
    subject: 'meccanica',
    level_it: 'Universitario · Base',
    level_en: 'University · Beginner',
    duration: '32h',
    lessons: 36,
    students: 1080,
    rating: 4.9,
    price: 139,
    type: 'ondemand',
    thumb: 'meccanica',
    short_it: 'Cinematica, dinamica, energia, urti, corpo rigido. Con problemi tipo esame.',
    short_en: 'Kinematics, dynamics, energy, collisions, rigid body. With exam-style problems.',
    tags_it: ['Università', 'Fisica', 'On-demand'],
    tags_en: ['University', 'Physics', 'On-demand'],
  },
  {
    id: 'em-2',
    title_it: 'Elettromagnetismo — Maxwell senza paura',
    title_en: 'Electromagnetism — Maxwell without fear',
    subject: 'em',
    level_it: 'Universitario · Intermedio',
    level_en: 'University · Intermediate',
    duration: '28h',
    lessons: 30,
    students: 720,
    rating: 4.8,
    price: 139,
    type: 'ondemand',
    thumb: 'em',
    short_it: 'Dalle leggi sperimentali alle equazioni di Maxwell. Onde, circuiti, magnetismo.',
    short_en: 'From experimental laws to Maxwell\'s equations. Waves, circuits, magnetism.',
    tags_it: ['Università', 'Fisica', 'On-demand'],
    tags_en: ['University', 'Physics', 'On-demand'],
  },
  {
    id: 'qm-intro',
    title_it: 'Introduzione alla Meccanica Quantistica',
    title_en: 'Introduction to Quantum Mechanics',
    subject: 'qm',
    level_it: 'Universitario · Avanzato',
    level_en: 'University · Advanced',
    duration: '20h',
    lessons: 22,
    students: 410,
    rating: 4.9,
    price: 169,
    type: 'ondemand',
    thumb: 'qm',
    short_it: 'Schrödinger, operatori, oscillatore armonico, atomo di idrogeno. Pensiero quantistico.',
    short_en: 'Schrödinger, operators, harmonic oscillator, hydrogen atom. Quantum thinking.',
    tags_it: ['Università', 'Fisica avanzata'],
    tags_en: ['University', 'Advanced physics'],
  },
  {
    id: 'maturita',
    title_it: 'Maturità Scientifica — Matematica & Fisica',
    title_en: 'High-school finals — Math & Physics',
    subject: 'maturita',
    level_it: 'Liceo · 5° anno',
    level_en: 'High-school · Year 5',
    duration: '45h',
    lessons: 50,
    students: 2150,
    rating: 4.9,
    price: 99,
    type: 'ondemand',
    thumb: 'maturita',
    short_it: 'Programma completo per la seconda prova. Simulazioni, tracce ufficiali, soluzioni passo passo.',
    short_en: 'Full prep for the final paper. Mock exams, official tracks, step-by-step solutions.',
    tags_it: ['Liceo', 'Maturità', 'Bestseller'],
    tags_en: ['High-school', 'Finals', 'Bestseller'],
    bestseller: true,
  },
  {
    id: 'tolc',
    title_it: 'TOLC-I & TOLC-E — strategia e velocità',
    title_en: 'University entrance — strategy & speed',
    subject: 'tolc',
    level_it: 'Test ammissione',
    level_en: 'Entrance test',
    duration: '18h',
    lessons: 24,
    students: 1340,
    rating: 4.8,
    price: 89,
    type: 'ondemand',
    thumb: 'tolc',
    short_it: 'Tecniche per fare in fretta. Logica, matematica, fisica e simulazioni cronometrate.',
    short_en: 'Techniques to be fast. Logic, math, physics and timed mock tests.',
    tags_it: ['Test', 'Università', 'Cronometrato'],
    tags_en: ['Test', 'University', 'Timed'],
  },
  {
    id: 'recupero',
    title_it: 'Recupero debito — Matematica liceo',
    title_en: 'Debt recovery — High-school math',
    subject: 'maturita',
    level_it: 'Liceo · Tutti gli anni',
    level_en: 'High-school · All years',
    duration: '20h',
    lessons: 24,
    students: 980,
    rating: 4.9,
    price: 79,
    type: 'ondemand',
    thumb: 'recupero',
    short_it: 'Programma personalizzato per recuperare il debito a settembre. Lezioni + esercizi corretti.',
    short_en: 'Custom program to recover summer debts. Lessons + corrected exercises.',
    tags_it: ['Liceo', 'Recupero', 'Estate'],
    tags_en: ['High-school', 'Recovery', 'Summer'],
  },
];

// Webinars
const WEBINARS = [
  {
    id: 'w1',
    title_it: 'Integrali impropri — la guida definitiva',
    title_en: 'Improper integrals — the definitive guide',
    subject: 'analisi',
    date: '2026-05-14T18:00:00',
    duration: '90 min',
    seats_total: 80,
    seats_left: 23,
    price: 0,
    mode: 'group',
    short_it: 'Sessione live: convergenza, criteri di confronto, esercizi tipo esame.',
    short_en: 'Live session: convergence, comparison criteria, exam-style problems.',
  },
  {
    id: 'w2',
    title_it: 'Maxwell in 90 minuti',
    title_en: 'Maxwell in 90 minutes',
    subject: 'em',
    date: '2026-05-21T19:00:00',
    duration: '90 min',
    seats_total: 100,
    seats_left: 47,
    price: 19,
    mode: 'group',
    short_it: 'Le 4 equazioni viste tutte insieme. Significato fisico e calcolo.',
    short_en: 'The 4 equations seen together. Physical meaning and computation.',
  },
  {
    id: 'w3',
    title_it: 'Sessione 1-1 · Preparazione esame',
    title_en: '1-on-1 · Exam prep',
    subject: 'analisi',
    date: '2026-05-12T15:00:00',
    duration: '60 min',
    seats_total: 1,
    seats_left: 1,
    price: 60,
    mode: 'one2one',
    short_it: 'Sessione privata, tu scegli l\'argomento. Registrazione inclusa.',
    short_en: 'Private session, you pick the topic. Recording included.',
  },
  {
    id: 'w4',
    title_it: 'Maturità: simulazione seconda prova',
    title_en: 'Finals: mock paper exam',
    subject: 'maturita',
    date: '2026-05-28T17:00:00',
    duration: '120 min',
    seats_total: 150,
    seats_left: 0,
    price: 25,
    mode: 'group',
    short_it: 'Prova ufficiale di un anno passato, risolta insieme. Tutti i passaggi.',
    short_en: 'A real past paper, solved together. Every step.',
  },
  {
    id: 'w5',
    title_it: 'Quantistica: l\'atomo di idrogeno',
    title_en: 'Quantum: the hydrogen atom',
    subject: 'qm',
    date: '2026-06-04T19:30:00',
    duration: '90 min',
    seats_total: 60,
    seats_left: 31,
    price: 29,
    mode: 'group',
    short_it: 'Soluzione dell\'equazione di Schrödinger per H. Numeri quantici, orbitali.',
    short_en: 'Solving the Schrödinger equation for H. Quantum numbers, orbitals.',
  },
];

// Testimonials
const TESTIMONIALS = [
  { name: 'Giulia M.', role_it: 'Ingegneria, Politecnico', role_en: 'Engineering, Politecnico', exam: 'Analisi 1', grade: '30L', stars: 5,
    text_it: 'Ho passato Analisi 1 con 30 e lode dopo due bocciature. Francesco spiega in modo che capisci davvero, non a memoria.',
    text_en: 'I passed Calc 1 with full marks after failing twice. Francesco explains so you actually understand, not by heart.' },
  { name: 'Marco R.', role_it: 'Liceo Scientifico, 5°', role_en: 'High-school, year 5', exam: 'Maturità', grade: '94/100', stars: 5,
    text_it: 'Avevo paura della seconda prova. Le simulazioni del corso erano identiche al livello reale. 94 di voto finale.',
    text_en: 'I was scared of the math paper. The course mock papers were spot on. 94 final grade.' },
  { name: 'Sofia L.', role_it: 'Medicina, test ammissione', role_en: 'Medicine, entrance test', exam: 'TOLC-MED', grade: 'Top 5%', stars: 5,
    text_it: 'Strategia di velocità imbattibile. Sono entrata al primo tentativo, top 5% nazionale.',
    text_en: 'Unbeatable speed strategy. Got in on the first try, top 5% nationally.' },
  { name: 'Luca P.', role_it: 'Fisica, Università', role_en: 'Physics, University', exam: 'Elettromagnetismo', grade: '29/30', stars: 5,
    text_it: 'Le equazioni di Maxwell mi sembravano arabo. Ora le uso. Il webinar di 90 minuti vale più di un mese di lezioni.',
    text_en: 'Maxwell\'s equations were Greek to me. Now I use them. The 90-min webinar is worth a month of class.' },
];

// Lessons (for player demo)
const PLAYER_LESSONS = [
  { id: 'l1', n: '01', t_it: 'Numeri reali — assiomi', t_en: 'Real numbers — axioms', dur: '12:30', done: true },
  { id: 'l2', n: '02', t_it: 'Successioni convergenti', t_en: 'Convergent sequences', dur: '18:45', done: true },
  { id: 'l3', n: '03', t_it: 'Limiti notevoli', t_en: 'Notable limits', dur: '22:10', done: true, current: true },
  { id: 'l4', n: '04', t_it: 'Forme indeterminate', t_en: 'Indeterminate forms', dur: '15:20', done: false },
  { id: 'l5', n: '05', t_it: 'Continuità di una funzione', t_en: 'Continuity of a function', dur: '19:05', done: false },
  { id: 'l6', n: '06', t_it: 'Teorema degli zeri', t_en: 'Zero theorem', dur: '14:50', done: false },
  { id: 'l7', n: '07', t_it: 'Derivata — definizione', t_en: 'Derivative — definition', dur: '21:15', done: false },
  { id: 'l8', n: '08', t_it: 'Regole di derivazione', t_en: 'Differentiation rules', dur: '17:40', done: false },
];

// Format date
const fmtDate = (iso, lang) => {
  const d = new Date(iso);
  const months_it = ['Gen','Feb','Mar','Apr','Mag','Giu','Lug','Ago','Set','Ott','Nov','Dic'];
  const months_en = ['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'];
  const m = lang === 'it' ? months_it : months_en;
  return `${d.getDate()} ${m[d.getMonth()]} · ${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`;
};

// Countdown helper
const timeUntil = (iso) => {
  const diff = new Date(iso) - new Date();
  if (diff <= 0) return { d:0, h:0, m:0, s:0, done: true };
  const d = Math.floor(diff / (1000*60*60*24));
  const h = Math.floor((diff / (1000*60*60)) % 24);
  const m = Math.floor((diff / (1000*60)) % 60);
  const s = Math.floor((diff / 1000) % 60);
  return { d, h, m, s, done: false };
};

Object.assign(window, { I18N, SUBJECTS, COURSES, WEBINARS, TESTIMONIALS, PLAYER_LESSONS, fmtDate, timeUntil });
